## HW 6 Pt 2
Author: Minji Kang <br>
Date: 3/29/2025 <br>
Description: EDA with sub-goal- Explore if any college programs consistently grow players with above-average or below-average advanced NBA metrics (Duke, Kentucky, Chapel Hill, etc.).

In [1]:
# importing pandas for dataframes
import pandas as pd
# importing geopandas for mapping
import geopandas
import geopy
from geopy.geocoders import Nominatim
import matplotlib.pyplot as plt

# Read in the merged dataset
mergedDF = pd.read_csv("https://raw.githubusercontent.com/hpatel-27/DataScience_CourseProject/refs/heads/main/datasets/merged_playerStats.csv", index_col=0)

# Read in players dataset
players = pd.read_csv("https://raw.githubusercontent.com/hpatel-27/DataScience_CourseProject/refs/heads/main/datasets/Players.csv", index_col=0)

In [2]:
mergedDF.columns

Index(['height', 'weight', 'college', 'Year', 'Pos', 'Age', 'G', 'MP', 'PER',
       'TS%', 'USG%', 'WS', 'BPM', 'VORP', 'FG%', '3P%', '2P%', 'eFG%', 'FT%',
       'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PTS'],
      dtype='object')

In [3]:
players.columns

Index(['Player', 'height', 'weight', 'collage', 'born', 'birth_city',
       'birth_state'],
      dtype='object')

In [10]:
# getting birth location from original players dataset since it was dropped for merged dataset
locationDF = players[['birth_city', 'birth_state']]
# setting index as player name
locationDF.index = players['Player']
# adding advanced metrics and college name
locationDF = locationDF.join(mergedDF[['college', 'BPM', 'VORP', 'WS']])
locationDF

,birth_city,birth_state,college,BPM,VORP,WS
Player,,,,,,
Curly Armstrong,NaN,NaN,Indiana University,NaN,NaN,2.408911
Cliff Barker,Yorktown,Indiana,University of Kentucky,NaN,NaN,0.677852
Leo Barnhorst,NaN,NaN,University of Notre Dame,NaN,NaN,NaN
Ed Bartels,NaN,NaN,North Carolina State University,NaN,NaN,-0.538298
Ralph Beard,Hardinsburg,Kentucky,University of Kentucky,NaN,NaN,5.690476
...,...,...,...,...,...,...
Troy Williams,Columbia,South Carolina,South Carolina State University,-2.76,-0.09,0.180000
Kyle Wiltjer,Portland,Oregon,Gonzaga University,-4.00,0.00,0.000000
Stephen Zimmerman,Hendersonville,Tennessee,"University of Nevada, Las Vegas",-7.30,-0.10,0.000000
Paul Zipser,Heidelberg,Germany,NaN,-3.70,-0.40,0.500000
Ivica Zubac,Mostar,Bosnia and Herzegovina,NaN,-2.50,-0.10,1.100000

In [11]:
# dropping row if birth location is not available
birthDF = locationDF.dropna(subset=['birth_state'])
birthDF

,birth_city,birth_state,college,BPM,VORP,WS
Player,,,,,,
Cliff Barker,Yorktown,Indiana,University of Kentucky,NaN,NaN,0.677852
Ralph Beard,Hardinsburg,Kentucky,University of Kentucky,NaN,NaN,5.690476
Charlie Black,Arco,Idaho,University of Kansas,NaN,NaN,1.877622
Nelson Bobb,Philadelphia,Pennsylvania,Temple University,NaN,NaN,1.521145
Jake Bornheimer,New Brunswick,New Jersey,Muhlenberg College,NaN,NaN,0.800000
...,...,...,...,...,...,...
Troy Williams,Columbia,South Carolina,South Carolina State University,-2.76,-0.09,0.180000
Kyle Wiltjer,Portland,Oregon,Gonzaga University,-4.00,0.00,0.000000
Stephen Zimmerman,Hendersonville,Tennessee,"University of Nevada, Las Vegas",-7.30,-0.10,0.000000
Paul Zipser,Heidelberg,Germany,NaN,-3.70,-0.40,0.500000
Ivica Zubac,Mostar,Bosnia and Herzegovina,NaN,-2.50,-0.10,1.100000

In [7]:
# dropping row if college is not available
collegeDF = locationDF.dropna(subset=['college'])
collegeDF

,birth_city,birth_state,college,BPM,VORP,WS,birth_loc
Player,,,,,,,
Curly Armstrong,NaN,NaN,Indiana University,NaN,NaN,2.408911,NaN
Cliff Barker,Yorktown,Indiana,University of Kentucky,NaN,NaN,0.677852,"Yorktown, Indiana"
Leo Barnhorst,NaN,NaN,University of Notre Dame,NaN,NaN,NaN,NaN
Ed Bartels,NaN,NaN,North Carolina State University,NaN,NaN,-0.538298,NaN
Ralph Beard,Hardinsburg,Kentucky,University of Kentucky,NaN,NaN,5.690476,"Hardinsburg, Kentucky"
...,...,...,...,...,...,...,...
Okaro White,Clearwater,Florida,Florida State University,-2.10,0.00,0.600000,"Clearwater, Florida"
Isaiah Whitehead,Brooklyn,New York,Seton Hall University,-4.90,-1.20,-0.800000,"Brooklyn, New York"
Troy Williams,Columbia,South Carolina,South Carolina State University,-2.76,-0.09,0.180000,"Columbia, South Carolina"
Kyle Wiltjer,Portland,Oregon,Gonzaga University,-4.00,0.00,0.000000,"Portland, Oregon"
Stephen Zimmerman,Hendersonville,Tennessee,"University of Nevada, Las Vegas",-7.30,-0.10,0.000000,"Hendersonville, Tennessee"

ValueError: could not convert string to float: 'Yorktown'